[build]
  publish = "./build/"
  command = "yarn build"
  functions = "./functions"

[context.production.environment]
  HEY_TEST = "prod"

[context.deploy-preview.environment]
  HEY_TEST = "deploy-preview"
