[build]
  publish = "./build/"
  command = "yarn build"
  functions = "./functions"

[[plugins]]
  package = 'netlify-plugin-contextual-env'

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    verbose = "true"
